### ISSUE TITLE
ios sim instructions

### ISSUE THREAD

**Issue by gedw99** [mearaj/saltyui#2]
android works, and also ios.

so if you want to add the ios instructions for the simulator 👍 

``` 
gogio -o saltyui.app -target ios .

# startup an IOS sim ( and wait for eternity )

xcrun simctl install booted saltyui.app

``` 

![Screenshot 2022-04-22 at 11 45 10](https://user-images.githubusercontent.com/53147028/164681584-74193c95-bb3e-47d1-9add-9b202c7cbd58.png)

**Comment by mearaj** [comment]
Fixed in commit 79338561, thanks :)
